const CHAT_WIDGET_SAFE_HEIGHT = 96;
const MOBILE_BOTTOM_NAV_HEIGHT = 56;

export const DESKTOP_BOTTOM_SAFE_AREA = CHAT_WIDGET_SAFE_HEIGHT;
export const MOBILE_BOTTOM_SAFE_AREA =
  CHAT_WIDGET_SAFE_HEIGHT + MOBILE_BOTTOM_NAV_HEIGHT;
