import { Box, Stack, Typography } from '@mui/material';
import {
  DataGridPremium,
  GridChartsIntegrationContextProvider,
  GridChartsRendererProxy,
  isAutogeneratedRow,
  type GridColumnVisibilityModel,
  type GridChartsPanelProps,
  type GridInitialState,
  type GridRowParams,
  type GridSortModel,
} from '@mui/x-data-grid-premium';
import {
  ChartsRenderer,
  configurationOptions,
  type ChartsRendererProps,
} from '@mui/x-charts-premium/ChartsRenderer';
import { useCallback, useMemo, useState } from 'react';
import type { CustomField } from '../GeneratedClient';
import type {
  ClientAssignmentRoleV2,
  ClientBrowserRowV2,
} from './useClientsBrowserViewModel';
import {
  clientsInternalSortVisibility,
  clientsGridSortSlotProps,
} from './clientsGridSorting';
import {
  buildClientsColumns,
  isOptionalClientsColumn,
} from './clientsGridColumns';
import { ClientsChartsPanel } from './ClientsChartsPanel';

type ClientsDataGridV2Props = {
  rows: ClientBrowserRowV2[];
  assignmentRoles: ClientAssignmentRoleV2[];
  familyCustomFields: CustomField[];
  caseCustomFields: CustomField[];
  countyOptions: string[];
  loading?: boolean;
  sortModel: GridSortModel;
  onSortModelChange: (model: GridSortModel) => void;
  onRowClick: (row: ClientBrowserRowV2) => void;
};

const clientsGridSlots = {
  noRowsOverlay: ClientsEmptyState,
};
const clientsGridSlotProps = {
  ...clientsGridSortSlotProps,
  chartsPanel: {
    schema: {
      bar: configurationOptions.bar,
      column: configurationOptions.column,
      pie: configurationOptions.pie,
    },
  },
};
const clientsGridInitialState: GridInitialState = {
  filter: {
    filterModel: { items: [], quickFilterExcludeHiddenColumns: false },
  },
};
const clientsGridSx = {
  '& .MuiDataGrid-row': { cursor: 'pointer', minHeight: 56 },
  '& .MuiDataGrid-cell': { alignItems: 'center', display: 'flex', py: 1 },
};
function getClientsRowHeight() {
  return 'auto' as const;
}
function getEstimatedClientsRowHeight() {
  return 72;
}

function ClientsEmptyState() {
  return (
    <Stack
      spacing={0.5}
      sx={{
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 180,
        px: 2,
        textAlign: 'center',
      }}
    >
      <Typography className="ph-unmask" variant="subtitle1">
        No client families found.
      </Typography>
      <Typography className="ph-unmask" color="text.secondary" variant="body2">
        Client families will appear here when they are available.
      </Typography>
    </Stack>
  );
}

export function ClientsDataGridV2({
  rows,
  assignmentRoles,
  familyCustomFields,
  caseCustomFields,
  countyOptions,
  loading = false,
  sortModel,
  onSortModelChange,
  onRowClick,
}: ClientsDataGridV2Props) {
  const [pivotActive, setPivotActive] = useState(false);
  const slots = useMemo(
    () => ({
      ...clientsGridSlots,
      chartsPanel: (props: GridChartsPanelProps) => (
        <ClientsChartsPanel {...props} pivotActive={pivotActive} />
      ),
    }),
    [pivotActive]
  );
  const renderChart = useCallback(
    (props: ChartsRendererProps) =>
      pivotActive && props.chartType ? (
        <Box sx={{ width: '100%', minWidth: 0, overflow: 'auto' }}>
          <ChartsRenderer {...props} />
        </Box>
      ) : null,
    [pivotActive]
  );
  const columns = useMemo(
    () =>
      buildClientsColumns(
        rows,
        assignmentRoles,
        familyCustomFields,
        caseCustomFields,
        countyOptions
      ),
    [rows, assignmentRoles, familyCustomFields, caseCustomFields, countyOptions]
  );
  const [columnVisibilityModel, setColumnVisibilityModel] =
    useState<GridColumnVisibilityModel>({});
  const visibleColumns = useMemo(
    () => ({
      ...Object.fromEntries(
        columns
          .filter((column) => isOptionalClientsColumn(column.field))
          .map((column) => [column.field, false])
      ),
      ...columnVisibilityModel,
      ...clientsInternalSortVisibility,
    }),
    [columns, columnVisibilityModel]
  );
  const handleRowClick = useCallback(
    ({ row }: GridRowParams<ClientBrowserRowV2>) => {
      if (!pivotActive && !isAutogeneratedRow(row) && row.familyId)
        onRowClick(row);
    },
    [onRowClick, pivotActive]
  );
  return (
    <GridChartsIntegrationContextProvider>
      <Box
        sx={{ height: '100%', width: '100%', minWidth: 0, overflowY: 'auto' }}
      >
        <Box sx={{ height: '100%', minHeight: 360 }}>
          <DataGridPremium
            showToolbar
            chartsIntegration
            disableRowGrouping
            disableAggregation
            pivotActive={pivotActive}
            onPivotActiveChange={setPivotActive}
            aggregationRowsScope="filtered"
            pagination={false}
            rows={rows}
            columns={columns}
            sortModel={pivotActive ? undefined : sortModel}
            onSortModelChange={pivotActive ? undefined : onSortModelChange}
            initialState={clientsGridInitialState}
            filterDebounceMs={200}
            columnVisibilityModel={visibleColumns}
            onColumnVisibilityModelChange={
              pivotActive ? undefined : setColumnVisibilityModel
            }
            columnHeaderHeight={42}
            density="comfortable"
            disableRowSelectionOnClick
            getRowHeight={getClientsRowHeight}
            getEstimatedRowHeight={getEstimatedClientsRowHeight}
            loading={loading}
            onRowClick={handleRowClick}
            slots={slots}
            slotProps={clientsGridSlotProps}
            sx={clientsGridSx}
          />
        </Box>
        <GridChartsRendererProxy
          id="clients-report"
          label="Client counts"
          renderer={renderChart}
        />
      </Box>
    </GridChartsIntegrationContextProvider>
  );
}
