import { Typography } from '@mui/material';
import {
  getGridBooleanOperators,
  getGridMultiSelectOperators,
  getGridSingleSelectOperators,
  isAutogeneratedRow,
  type GridColDef,
  type GridFilterOperator,
} from '@mui/x-data-grid-premium';
import { CustomFieldType, type CustomField } from '../GeneratedClient';
import { v2Typography } from '../Families/v2Typography';
import { simplify } from '../Utilities/stringUtils';
import { ClientFamilyCellV2 } from './ClientFamilyCellV2';
import { ClientArrangementSummaryCellV2 } from './ClientArrangementSummaryCellV2';
import { clientsInternalSortColumns } from './clientsGridSorting';
import type {
  ClientAssignmentRoleV2,
  ClientBrowserRowV2,
  ClientCustomFieldValue,
} from './useClientsBrowserViewModel';

type Option = { value: string; label: string };
const maximumCategoricalReportingOptions = 50;

const multipleSelectionOperator = getGridSingleSelectOperators().find(
  (operator) => operator.value === 'isAnyOf'
)!;

function emptyOperators<
  V extends ClientCustomFieldValue,
  F = V,
>(): GridFilterOperator<ClientBrowserRowV2, V, F>[] {
  return [
    {
      value: 'isEmpty',
      requiresFilterValue: false,
      getApplyFilterFn: () => (value) =>
        value === null ||
        value === '' ||
        (Array.isArray(value) && value.length === 0),
    },
    {
      value: 'isNotEmpty',
      requiresFilterValue: false,
      getApplyFilterFn: () => (value) =>
        value !== null &&
        value !== '' &&
        (!Array.isArray(value) || value.length > 0),
    },
  ];
}

const arrayFilterOperators: GridFilterOperator<
  ClientBrowserRowV2,
  string[] | null,
  string
>[] = getGridMultiSelectOperators().map((operator) => ({
  ...operator,
  getApplyFilterFn: (item, column) => {
    const apply = operator.getApplyFilterFn(item, column);
    if (
      !apply ||
      (operator.value !== 'contains' && operator.value !== 'doesNotContain')
    )
      return apply;
    return (entries, row, definition, apiRef) =>
      apply(entries?.length ? entries : [''], row, definition, apiRef);
  },
}));

function formatValue(value: ClientCustomFieldValue) {
  if (value === null) return '';
  if (Array.isArray(value)) return value.join(', ');
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  return value;
}

function normalizedQuickFilter(value: unknown) {
  const query = simplify(String(value));
  return (cell: string) => simplify(cell ?? '').includes(query);
}

function arrayColumn(
  field: string,
  headerName: string,
  options: Option[],
  getValue: (row: ClientBrowserRowV2) => string[] | null,
  blankLabel = '(blank)'
): GridColDef<ClientBrowserRowV2, string[] | null, string> {
  const labels = new Map(options.map((option) => [option.value, option.label]));
  const format = (values: string[] | null) =>
    (values ?? []).map((value) => labels.get(value) ?? value).join(', ');
  return {
    field,
    headerName,
    type: 'multiSelect',
    minWidth: 180,
    flex: 1,
    valueOptions: [{ value: '', label: blankLabel }, ...options],
    valueGetter: (_value, row) => getValue(row),
    valueFormatter: (value) => format(value),
    sortComparator: (first, second) =>
      format(first).localeCompare(format(second)),
    filterOperators: arrayFilterOperators,
    getApplyQuickFilterFn: (value) => {
      const query = simplify(String(value));
      return (entries) => simplify(format(entries)).includes(query);
    },
    renderCell: ({ formattedValue }) => (
      <Typography {...v2Typography.browserCell}>
        {formattedValue || '-'}
      </Typography>
    ),
  };
}

function customFieldColumns(
  fields: CustomField[],
  scope: 'case' | 'family',
  rows: ClientBrowserRowV2[]
): GridColDef<ClientBrowserRowV2>[] {
  return fields.map((definition) => {
    const field = `${scope === 'case' ? 'caseCustomField' : 'customField'}:${definition.name}`;
    const headerName = `${scope === 'case' ? 'Case' : 'Family'}: ${definition.name}`;
    const getValue = (row: ClientBrowserRowV2) =>
      (scope === 'case' ? row.caseCustomFieldValues : row.customFieldValues)[
        definition.name
      ] ?? null;
    if (definition.type === CustomFieldType.StringArray) {
      const options = Array.from(
        new Set([
          ...(definition.validValues ?? []),
          ...rows.flatMap((row) => {
            const value = getValue(row);
            return Array.isArray(value) ? value : [];
          }),
        ])
      ).map((value) => ({ value, label: value }));
      return arrayColumn(field, headerName, options, (row) => {
        const value = getValue(row);
        return Array.isArray(value) ? value : null;
      });
    }
    if (
      definition.type === CustomFieldType.String &&
      definition.validValues?.length
    ) {
      const configuredValues = new Set(definition.validValues);
      const observedValues = rows.map(getValue);
      const pivotable =
        configuredValues.size <= maximumCategoricalReportingOptions &&
        observedValues.every(
          (value) =>
            value === null ||
            value === '' ||
            configuredValues.has(String(value))
        );
      return {
        field,
        headerName,
        type: 'singleSelect',
        minWidth: 180,
        flex: 1,
        valueOptions: Array.from(
          new Set([
            ...configuredValues,
            ...observedValues.filter(
              (value): value is string => typeof value === 'string'
            ),
          ])
        ),
        pivotable,
        chartable: pivotable && observedValues.every((value) => value !== null),
        valueGetter: (_value, row) => getValue(row),
        valueFormatter: (value: string | null) => value ?? '',
        filterOperators: [
          ...getGridSingleSelectOperators(),
          ...emptyOperators<string | null>(),
        ],
      };
    }
    return {
      field,
      headerName,
      minWidth: 180,
      flex: 1,
      type: definition.type === CustomFieldType.Boolean ? 'boolean' : 'string',
      pivotable: definition.type === CustomFieldType.Boolean,
      chartable:
        definition.type === CustomFieldType.Boolean &&
        rows.every((row) => getValue(row) !== null),
      ...(definition.type === CustomFieldType.Boolean
        ? {
            filterOperators: [
              ...getGridBooleanOperators(),
              ...emptyOperators<boolean | null>(),
            ],
          }
        : {}),
      valueGetter: (_value, row) => getValue(row),
      valueFormatter: (value: ClientCustomFieldValue) => formatValue(value),
      renderCell: ({ value }) => (
        <Typography {...v2Typography.browserCell}>
          {formatValue(value) || '-'}
        </Typography>
      ),
    };
  });
}

export function buildClientsColumns(
  rows: ClientBrowserRowV2[],
  assignmentRoles: ClientAssignmentRoleV2[],
  familyCustomFields: CustomField[],
  caseCustomFields: CustomField[],
  countyOptions: string[]
): GridColDef<ClientBrowserRowV2>[] {
  const nameComparator = clientsInternalSortColumns.find(
    (column) => column.field === 'primaryContactFirstName'
  )!.sortComparator;
  const columns: GridColDef<ClientBrowserRowV2>[] = [
    ...clientsInternalSortColumns,
    {
      field: 'clientCount',
      headerName: 'Client count',
      type: 'number',
      width: 140,
      pivotable: true,
      aggregable: true,
      availableAggregationFunctions: ['sum'],
      getApplyQuickFilterFn: () => null,
    },
    {
      field: 'family',
      headerName: 'Family',
      flex: 1.3,
      minWidth: 220,
      getApplyQuickFilterFn: normalizedQuickFilter,
      renderCell: ({ row }) => (
        <ClientFamilyCellV2
          familyName={row.family || '-'}
          phoneNumber={row.phoneNumber}
          primaryContactName={row.primaryContactName}
        />
      ),
    },
    {
      field: 'memberNames',
      headerName: 'Family members',
      minWidth: 240,
      getApplyQuickFilterFn: normalizedQuickFilter,
    },
    {
      field: 'firstName',
      headerName: 'Primary contact first name',
      minWidth: 200,
      valueGetter: (_value, row) => row.primaryContactFirstName,
      sortComparator: nameComparator,
    },
    {
      field: 'lastName',
      headerName: 'Primary contact last name',
      minWidth: 200,
      valueGetter: (_value, row) => row.primaryContactLastName,
      sortComparator: nameComparator,
    },
    {
      field: 'dateOpened',
      headerName: 'Date opened',
      description:
        'Open case date, or the selected open referral creation date.',
      type: 'dateTime',
      minWidth: 180,
      valueGetter: (_value, row) =>
        row.openedAtTime === null ? null : new Date(row.openedAtTime),
    },
    {
      field: 'caseStatus',
      pivotable: true,
      headerName: 'Case status',
      type: 'singleSelect',
      valueOptions: ['Open', 'Closed', 'No case'],
      minWidth: 150,
      flex: 1,
      renderCell: ({ row }) => (
        <Typography {...v2Typography.browserCell} noWrap>
          {row.status || '-'}
        </Typography>
      ),
    },
    arrayColumn(
      'arrangementStatuses',
      'Arrangement status',
      ['Intake', 'Active', 'Setup'].map((value) => ({ value, label: value })),
      (row) => row.arrangementStatuses
    ),
    {
      field: 'county',
      pivotable: true,
      headerName: 'County',
      type: 'singleSelect',
      minWidth: 140,
      flex: 1,
      valueOptions: [{ value: '', label: '(blank)' }, ...countyOptions],
      filterOperators: [multipleSelectionOperator, ...emptyOperators<string>()],
      valueFormatter: (value: string) => value,
      renderCell: ({ value }) => (
        <Typography {...v2Typography.browserCell}>{value || '-'}</Typography>
      ),
    },
    ...assignmentRoles.map(({ role, options }) => ({
      ...arrayColumn(
        `assignmentRole:${role}`,
        role,
        options,
        (row) => row.assignmentPersonIds[role] ?? [],
        'Unassigned'
      ),
      renderCell: ({ row }: { row: ClientBrowserRowV2 }) => (
        <Typography {...v2Typography.browserCell}>
          {row.assignmentRoleValues[role] || '-'}
        </Typography>
      ),
    })),
    ...customFieldColumns(familyCustomFields, 'family', rows),
    ...customFieldColumns(caseCustomFields, 'case', rows),
    {
      field: 'arrangements',
      headerName: 'Arrangements',
      flex: 1.4,
      minWidth: 260,
      renderCell: ({ row }) => (
        <ClientArrangementSummaryCellV2 arrangementRows={row.arrangementRows} />
      ),
    },
    arrayColumn(
      'arrangementTypes',
      'Arrangement types',
      Array.from(new Set(rows.flatMap((row) => row.arrangementTypes))).map(
        (value) => ({ value, label: value })
      ),
      (row) => row.arrangementTypes
    ),
  ];
  return columns.map((column) => ({
    chartable: column.pivotable === true,
    pivotable: false,
    aggregable: false,
    availableAggregationFunctions: [],
    ...column,
    ...(column.valueGetter && {
      valueGetter: (value, row, definition, apiRef) =>
        isAutogeneratedRow(row)
          ? null
          : column.valueGetter!(value, row, definition, apiRef),
    }),
    ...(column.renderCell && {
      renderCell: (params) => {
        if (isAutogeneratedRow(params.row)) {
          return typeof params.value === 'string' ||
            typeof params.value === 'number'
            ? params.value
            : typeof params.value === 'boolean'
              ? formatValue(params.value)
              : null;
        }
        return column.renderCell!(params);
      },
    }),
  }));
}

export function isOptionalClientsColumn(field: string) {
  return (
    [
      'clientCount',
      'memberNames',
      'firstName',
      'lastName',
      'dateOpened',
      'arrangementStatuses',
      'arrangementTypes',
    ].includes(field) ||
    field.startsWith('customField:') ||
    field.startsWith('caseCustomField:')
  );
}
