import { Box, useTheme } from '@mui/material';
import {
  DataGridPremium,
  GridChartsIntegrationContextProvider,
  GridChartsRendererProxy,
  isAutogeneratedRow,
  type GridChartsPanelProps,
  type GridRowSelectionModel,
} from '@mui/x-data-grid-premium';
import {
  ChartsRenderer,
  configurationOptions,
  type ChartsRendererProps,
} from '@mui/x-charts-premium/ChartsRenderer';
import { useCallback, useMemo } from 'react';
import { v2DataGridStyles } from '../Families/v2DataGridStyles';
import {
  buildVolunteersGridColumns,
  VOLUNTEERS_SEARCH_FIELD,
} from './volunteersGridColumns';
import type { VolunteerBrowserRowV2 } from './useVolunteersBrowserViewModel';
import { VolunteersChartsPanel } from './VolunteersChartsPanel';
import { usePersistedGridFilterModel } from '../Hooks/usePersistedGridFilterModel';
import { notAppliedRoleFilterValue } from './roleFilterValues';

type Props = {
  arrangementTypes: string[];
  familyCustomFields: Parameters<
    typeof buildVolunteersGridColumns
  >[0]['familyCustomFields'];
  loading?: boolean;
  onRowClick: (row: VolunteerBrowserRowV2) => void;
  onRowSelectionModelChange: (model: GridRowSelectionModel) => void;
  onPivotActiveChange: (active: boolean) => void;
  roleNames: string[];
  rowSelectionModel: GridRowSelectionModel;
  rows: VolunteerBrowserRowV2[];
  updateTestFamilyFlagEnabled?: boolean;
  pivotActive: boolean;
  volunteerCustomFields: Parameters<
    typeof buildVolunteersGridColumns
  >[0]['volunteerCustomFields'];
};

export function VolunteersDataGridV2({
  arrangementTypes,
  familyCustomFields,
  loading = false,
  onRowClick,
  onRowSelectionModelChange,
  onPivotActiveChange,
  roleNames,
  rowSelectionModel,
  rows,
  updateTestFamilyFlagEnabled,
  pivotActive,
  volunteerCustomFields,
}: Props) {
  const theme = useTheme();
  const columns = useMemo(
    () =>
      buildVolunteersGridColumns({
        arrangementTypes,
        familyCustomFields,
        rows,
        roleNames,
        updateTestFamilyFlagEnabled,
        volunteerCustomFields,
      }),
    [
      arrangementTypes,
      familyCustomFields,
      roleNames,
      rows,
      updateTestFamilyFlagEnabled,
      volunteerCustomFields,
    ]
  );
  const columnVisibilityModel = useMemo(
    () =>
      Object.fromEntries([
        [VOLUNTEERS_SEARCH_FIELD, false],
        ['volunteerFamilyCount', false],
        ...arrangementTypes.map((type) => [
          `arrangementAssignment:${type}`,
          false,
        ]),
        ...roleNames
          .filter((roleName) => roleName !== notAppliedRoleFilterValue)
          .map((roleName) => [`roleStatus:${roleName}`, false]),
        ...familyCustomFields.map((field) => [
          `familyCustomField:${field.name}`,
          false,
        ]),
        ...volunteerCustomFields.map((field) => [
          `volunteerCustomField:${field.name}`,
          false,
        ]),
      ]),
    [arrangementTypes, familyCustomFields, roleNames, volunteerCustomFields]
  );
  const gridConfigurationKey = useMemo(
    () =>
      JSON.stringify([
        rows.length === 0,
        columns.map(({ chartable, field, pivotable, type }) => [
          field,
          type,
          pivotable,
          chartable,
        ]),
      ]),
    [columns, rows.length]
  );
  const slots = useMemo(
    () => ({
      chartsPanel: (props: GridChartsPanelProps) => (
        <VolunteersChartsPanel {...props} pivotActive={pivotActive} />
      ),
    }),
    [pivotActive]
  );
  const renderChart = useCallback(
    (props: ChartsRendererProps) =>
      pivotActive && props.chartType ? (
        <Box sx={{ minWidth: 0, overflow: 'auto', width: '100%' }}>
          <ChartsRenderer {...props} />
        </Box>
      ) : null,
    [pivotActive]
  );
  const { filterModel, onFilterModelChange } = usePersistedGridFilterModel({
    columns,
    namespace: 'volunteers',
  });

  return (
    <GridChartsIntegrationContextProvider key={gridConfigurationKey}>
      <Box sx={v2DataGridStyles(theme, { height: '100%' })}>
        <DataGridPremium
          showToolbar
          chartsIntegration
          pivotActive={pivotActive}
          onPivotActiveChange={onPivotActiveChange}
          aggregationRowsScope="filtered"
          disableRowGrouping
          pagination
          rows={rows}
          columns={columns}
          filterModel={filterModel}
          onFilterModelChange={onFilterModelChange}
          slots={slots}
          loading={loading}
          getEstimatedRowHeight={() => 88}
          getRowHeight={() => 'auto'}
          columnHeaderHeight={42}
          checkboxSelection={!pivotActive}
          disableRowSelectionOnClick
          disableRowSelectionExcludeModel
          onRowClick={({ row }) => {
            if (!pivotActive && !isAutogeneratedRow(row)) onRowClick(row);
          }}
          onRowSelectionModelChange={onRowSelectionModelChange}
          pageSizeOptions={[25, 50, 100]}
          rowSelectionModel={rowSelectionModel}
          initialState={{
            pagination: { paginationModel: { pageSize: 100 } },
            sorting: { sortModel: [{ field: 'family', sort: 'asc' }] },
            columns: { columnVisibilityModel },
          }}
          slotProps={{
            chartsPanel: {
              schema: {
                bar: configurationOptions.bar,
                column: configurationOptions.column,
                pie: configurationOptions.pie,
              },
            },
            toolbar: {
              quickFilterProps: {
                quickFilterParser: (value: string) => (value ? [value] : []),
              },
            },
            baseCheckbox: {
              slotProps: {
                htmlInput: { title: 'Select families to enable bulk actions.' },
              },
            },
          }}
        />
      </Box>
      <GridChartsRendererProxy
        id="volunteers-report"
        label="Volunteer family counts"
        renderer={renderChart}
      />
    </GridChartsIntegrationContextProvider>
  );
}
