import { expect, test } from '@playwright/test';
import { build } from 'rolldown';
import { fileURLToPath } from 'node:url';
import { GRID_ID_AUTOGENERATED } from '@mui/x-data-grid/internals';
import { Community, OrganizationCategory } from '../src/GeneratedClient';
import {
  buildOrganizationsGridColumns,
  canNavigateOrganizationRow,
  categoryLabelsForGrid,
  categoryLabelsForDisplay,
  organizationGridExportFields,
  organizationGridFeatureProps,
  organizationGridInitialSortModel,
} from '../src/Communities/organizationsGridColumns';
import { buildOrganizationGridRows } from '../src/Communities/organizationsDataGridViewModel';

let bundle: string;

test.beforeAll(async () => {
  const result = await build({
    input: fileURLToPath(
      new URL('./organizations-grid-harness.tsx', import.meta.url)
    ),
    platform: 'browser',
    tsconfig: false,
    transform: {
      jsx: { runtime: 'automatic' },
      define: { 'process.env.NODE_ENV': JSON.stringify('production') },
    },
    plugins: [
      {
        name: 'exclude-local',
        resolveId(source) {
          if (source.split(/[\\/]/).some((part) => part.includes('.local')))
            throw new Error('Excluded path');
          return null;
        },
      },
    ],
    output: { format: 'iife' },
    write: false,
  });
  const output = result.output.find((item) => item.type === 'chunk');
  if (!output || output.type !== 'chunk')
    throw new Error('Missing browser bundle');
  bundle = output.code;
});

async function mountOrganizationsGrid(page: import('@playwright/test').Page) {
  await page.goto('/');
  await page.setContent('<html><body><div id="root"></div></body></html>');
  await page.addScriptTag({ content: bundle });
  await expect(page.getByRole('grid')).toBeVisible();
}

function community({
  id,
  name,
  description = '',
  categoryIds = [],
  memberFamilyCount = 0,
  roleAssignmentCount = 0,
}: {
  id: string;
  name: string;
  description?: string;
  categoryIds?: string[];
  memberFamilyCount?: number;
  roleAssignmentCount?: number;
}) {
  return Community.fromJS({
    id,
    name,
    description,
    categoryIds,
    memberFamilies: Array.from(
      { length: memberFamilyCount },
      (_, index) => `${index}`
    ),
    communityRoleAssignments: Array.from(
      { length: roleAssignmentCount },
      (_, index) => ({ personId: `${index}`, roleId: `role-${index}` })
    ),
  });
}

test('builds one operational-grid row per community with safe category labels and numeric counts', () => {
  const housing = OrganizationCategory.fromJS({
    id: 'housing',
    name: 'Housing',
  });
  const advocacy = OrganizationCategory.fromJS({
    id: 'advocacy',
    name: 'advocacy',
  });
  const rows = buildOrganizationGridRows(
    [
      community({
        id: 'organization-b',
        name: 'Beta Organization',
        description: 'Second organization',
        categoryIds: ['housing', 'missing', 'advocacy'],
        memberFamilyCount: 2,
        roleAssignmentCount: 3,
      }),
      community({ id: 'organization-a', name: 'Alpha Organization' }),
    ],
    new Map([
      [housing.id, housing],
      [advocacy.id, advocacy],
    ])
  );

  expect(rows).toEqual([
    {
      id: 'organization-b',
      name: 'Beta Organization',
      description: 'Second organization',
      categoryLabels: ['advocacy', 'Housing'],
      memberFamilyCount: 2,
      organizationCount: 1,
      roleAssignmentCount: 3,
    },
    {
      id: 'organization-a',
      name: 'Alpha Organization',
      description: '',
      categoryLabels: [],
      memberFamilyCount: 0,
      organizationCount: 1,
      roleAssignmentCount: 0,
    },
  ]);
  expect(organizationGridInitialSortModel).toEqual([
    { field: 'name', sort: 'asc' },
  ]);
});

test('exposes Pivot and Charts reporting measures without changing operational exports', () => {
  const columns = buildOrganizationsGridColumns({
    organizationCategoriesEnabled: true,
  });
  const withoutCategories = buildOrganizationsGridColumns({
    organizationCategoriesEnabled: false,
  });
  const memberFamiliesColumn = columns.find(
    (column) => column.field === 'memberFamilyCount'
  );
  const roleAssignmentsColumn = columns.find(
    (column) => column.field === 'roleAssignmentCount'
  );
  const organizationCountColumn = columns.find(
    (column) => column.field === 'organizationCount'
  );
  const nameColumn = columns.find((column) => column.field === 'name');
  const descriptionColumn = columns.find(
    (column) => column.field === 'description'
  );
  const categoriesColumn = columns.find(
    (column) => column.field === 'categoryLabels'
  );

  expect(columns.map((column) => column.field)).toEqual([
    'name',
    'description',
    'categoryLabels',
    'memberFamilyCount',
    'roleAssignmentCount',
    'organizationCount',
  ]);
  expect(withoutCategories.map((column) => column.field)).not.toContain(
    'categoryLabels'
  );
  expect(categoryLabelsForDisplay(['Housing', 'Advocacy'])).toBe(
    'Housing, Advocacy'
  );
  expect(memberFamiliesColumn?.type).toBe('number');
  expect(roleAssignmentsColumn?.type).toBe('number');
  expect(organizationCountColumn).toMatchObject({
    aggregable: true,
    availableAggregationFunctions: ['sum'],
    chartable: true,
    disableExport: true,
    pivotable: false,
  });
  expect(organizationCountColumn?.getApplyQuickFilterFn).toBeDefined();
  expect(nameColumn).toMatchObject({
    aggregable: false,
    chartable: true,
    pivotable: true,
  });
  expect(descriptionColumn).toMatchObject({
    aggregable: false,
    chartable: false,
    groupable: false,
    pivotable: false,
  });
  expect(categoriesColumn).toMatchObject({
    aggregable: false,
    chartable: false,
    groupable: false,
    pivotable: false,
  });
  [memberFamiliesColumn, roleAssignmentsColumn].forEach((column) =>
    expect(column).toMatchObject({
      aggregable: true,
      availableAggregationFunctions: ['sum'],
      chartable: true,
      pivotable: false,
    })
  );
  expect(organizationGridExportFields).toEqual([
    'name',
    'description',
    'categoryLabels',
    'memberFamilyCount',
    'roleAssignmentCount',
  ]);
  expect(organizationGridFeatureProps).toEqual({
    disableAggregation: true,
    disableRowGrouping: true,
    disableRowSelectionOnClick: true,
  });
});

test('keeps generated Pivot rows out of organization navigation and category access', () => {
  const generatedRow = {
    [GRID_ID_AUTOGENERATED]: 'generated-organization-row',
    id: 'generated-organization-row',
    name: '',
    description: '',
    categoryLabels: [],
    memberFamilyCount: 0,
    organizationCount: 0,
    roleAssignmentCount: 0,
  };
  expect(canNavigateOrganizationRow(generatedRow, false)).toBe(false);
  expect(canNavigateOrganizationRow(generatedRow, true)).toBe(false);
  expect(categoryLabelsForGrid(generatedRow)).toBeNull();
});

test('uses native Quick Filter and opens organizations through mouse and keyboard activation', async ({
  page,
}) => {
  await mountOrganizationsGrid(page);

  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('searchbox').first().fill('Beta Organization');
  await expect(
    page.getByRole('gridcell', { name: 'Alpha Organization', exact: true })
  ).toHaveCount(0);
  await expect(
    page.getByRole('gridcell', { name: 'Beta Organization', exact: true })
  ).toBeVisible();

  await page.getByRole('searchbox').first().fill('');
  await page
    .getByRole('gridcell', { name: 'Beta Organization', exact: true })
    .click();
  await expect(page).toHaveURL(
    /organizations\/organization\/organization-beta$/
  );

  await mountOrganizationsGrid(page);
  const alphaNameCell = page.getByRole('gridcell', {
    name: 'Alpha Organization',
    exact: true,
  });
  await alphaNameCell.focus();
  await page.keyboard.press('Enter');
  await expect(page).toHaveURL(
    /organizations\/organization\/organization-alpha$/
  );
});
