import { expect, test } from '@playwright/test';
import {
  GRID_AGGREGATION_FUNCTIONS,
  GridLogicOperator,
  gridDateComparator,
  gridStringOrNumberComparator,
  type GridFilterModel,
  type GridApiPremium,
  type GridColDef,
} from '@mui/x-data-grid-premium';
import { GRID_ID_AUTOGENERATED } from '@mui/x-data-grid/internals';
import { gridChartableColumnsSelector } from '../node_modules/@mui/x-data-grid-premium/hooks/features/chartsIntegration/gridChartsIntegrationSelectors';
import { serializeCellValue } from '../node_modules/@mui/x-data-grid/hooks/features/export/serializers/csvSerializer';
import {
  buildAggregatedFilterApplier,
  passFilterLogic,
} from '../node_modules/@mui/x-data-grid/hooks/features/filter/gridFilterUtils';
import { serializeRowUnsafe } from '../node_modules/@mui/x-data-grid-premium/hooks/features/export/serializer/excelSerializer';
import {
  createPivotPropsFromRows,
  getInitialColumns,
} from '../node_modules/@mui/x-data-grid-premium/hooks/features/pivoting/utils';
import { CustomField, CustomFieldType } from '../src/GeneratedClient';
import {
  buildReferralsColumns,
  isOptionalReferralsColumn,
} from '../src/V1Referrals/referralsGridColumns';
import type { ReferralBrowserRowV2 } from '../src/V1Referrals/referralBrowserTypes';

function row(
  id: string,
  overrides: Partial<ReferralBrowserRowV2> = {}
): ReferralBrowserRowV2 {
  return {
    id,
    referralCount: 1,
    title: 'Referral',
    status: 'OPEN',
    openedAtUtc: new Date('2026-01-01'),
    acceptedAtUtc: null,
    closedAtUtc: null,
    clientFamilyName: 'Same family',
    county: 'North',
    comments: '',
    searchableText: 'Referral',
    assignmentPersonIdsByRole: {},
    assignmentNamesByRole: {},
    customFieldValues: {},
    ...overrides,
  };
}

const field = (name: string, type: CustomFieldType, validValues?: string[]) =>
  new CustomField({ name, type, validValues });
const columns = (rows: ReferralBrowserRowV2[], fields: CustomField[] = []) =>
  buildReferralsColumns(rows, [], fields, ['North', 'South'], false);

function pivot(
  rows: ReferralBrowserRowV2[],
  definitions: GridColDef<ReferralBrowserRowV2>[],
  dimension = 'status',
  columnDimension?: string
) {
  const apiRef = {
    current: {
      state: { pivoting: { active: true } },
      getRowValue: (
        record: ReferralBrowserRowV2,
        column: GridColDef<ReferralBrowserRowV2>
      ): unknown =>
        column.valueGetter
          ? column.valueGetter(undefined as never, record, column, apiRef)
          : record[column.field as keyof ReferralBrowserRowV2],
      getRowFormattedValue: (
        record: ReferralBrowserRowV2,
        column: GridColDef<ReferralBrowserRowV2>
      ): unknown => {
        const value = apiRef.current.getRowValue(record, column);
        return column.valueFormatter
          ? column.valueFormatter(value as never, record, column, apiRef)
          : value;
      },
    } as unknown as GridApiPremium,
  };
  return createPivotPropsFromRows({
    rows,
    columns: getInitialColumns(
      definitions,
      undefined,
      (() => '') as GridApiPremium['getLocaleText']
    ),
    pivotModel: {
      rows: [{ field: dimension }],
      columns: columnDimension ? [{ field: columnDimension }] : [],
      values: [{ field: 'referralCount', aggFunc: 'sum' }],
    },
    apiRef,
  });
}

test('derives reporting eligibility for three configurations and newly added fields', () => {
  const configA = [
    field('Program', CustomFieldType.String, ['A', 'B']),
    field('Stable', CustomFieldType.Boolean),
    field('Notes', CustomFieldType.String),
    field('Needs', CustomFieldType.StringArray),
  ];
  const a = columns(
    [
      row('1', {
        customFieldValues: {
          Program: 'A',
          Stable: false,
          Notes: 'private',
          Needs: ['Food'],
        },
      }),
    ],
    configA
  );
  const b = columns(
    [row('1', { customFieldValues: { Region: 'East' } })],
    [field('Region', CustomFieldType.String, ['East'])]
  );
  const c = columns([row('1')]);
  for (const name of ['Program', 'Stable']) {
    expect(
      a.find((column) => column.field === `referralCustomField:${name}`)
    ).toMatchObject({ pivotable: true, chartable: true });
  }
  for (const name of ['Notes', 'Needs']) {
    expect(
      a.find((column) => column.field === `referralCustomField:${name}`)
    ).toMatchObject({ pivotable: false, chartable: false });
  }
  expect(b.find((column) => column.field.endsWith(':Region'))).toMatchObject({
    pivotable: true,
    chartable: true,
  });
  expect(b.some((column) => column.field.endsWith(':Program'))).toBe(false);
  expect(
    c.some((column) => column.field.startsWith('referralCustomField:'))
  ).toBe(false);
  const added = columns(
    [row('1', { customFieldValues: { New: true } })],
    [field('New', CustomFieldType.Boolean)]
  );
  expect(added.find((column) => column.field.endsWith(':New'))).toMatchObject({
    pivotable: true,
    chartable: true,
  });
});

test('keeps nulls pivotable, excludes null chart dimensions and unexpected categories', () => {
  const definitions = [
    field('Flag', CustomFieldType.Boolean),
    field('Category', CustomFieldType.String, ['Known']),
  ];
  const built = columns(
    [
      row('1', {
        county: null,
        customFieldValues: { Flag: null, Category: 'Unexpected' },
      }),
    ],
    definitions
  );
  expect(built.find((column) => column.field === 'county')).toMatchObject({
    pivotable: true,
    chartable: false,
  });
  expect(built.find((column) => column.field.endsWith(':Flag'))).toMatchObject({
    pivotable: true,
    chartable: false,
  });
  expect(
    built.find((column) => column.field.endsWith(':Category'))
  ).toMatchObject({ type: 'string', pivotable: false, chartable: false });
  const large = columns(
    [row('1')],
    [
      field(
        'Large',
        CustomFieldType.String,
        Array.from({ length: 51 }, (_, i) => String(i))
      ),
    ]
  );
  expect(
    large.find((column) => column.field.endsWith(':Large'))?.pivotable
  ).toBe(false);
});

test('native Pivot preserves referral identity, missing dimensions and exact numeric counts', () => {
  const rows = [
    row('1'),
    row('2', { status: 'ACCEPTED' }),
    row('3', { clientFamilyName: null, county: null }),
  ];
  const original = structuredClone(rows);
  const result = pivot(rows, columns(rows), 'county', 'status');
  expect(result.rows.map((record) => record.id)).toEqual(['1', '2', '3']);
  const measures = Object.keys(result.aggregationModel!);
  const total = measures.reduce(
    (sum, measure) =>
      sum +
      GRID_AGGREGATION_FUNCTIONS.sum.apply({
        values: result.rows.map((record) => record[measure]),
        field: measure,
      }),
    0
  );
  expect(total).toBe(3);
  expect(rows).toEqual(original);
  expect(result.columnGroupingModel?.map((group) => group.headerName)).toEqual([
    'Open',
    'Accepted',
  ]);
  expect(isOptionalReferralsColumn('referralCount')).toBe(true);
});

test('native quick-filter and status predicates feed the same Pivot count measure', () => {
  const rows = [
    row('1', { searchableText: 'needle' }),
    row('2', { searchableText: 'needle', status: 'CLOSED' }),
    row('3'),
  ];
  const built = columns(rows);
  const search = built.find((column) => column.field === 'searchableText')!;
  const apiRef = { current: undefined as unknown as GridApiPremium };
  const predicate = search.getApplyQuickFilterFn!(' NEEDLE ', search, apiRef)!;
  const matching = rows.filter((record) =>
    predicate(record.searchableText, record, search, apiRef)
  );
  const result = pivot(matching, built);
  expect(
    GRID_AGGREGATION_FUNCTIONS.sum.apply({
      values: result.rows.map((record) => record.referralCount),
      field: 'referralCount',
    })
  ).toBe(2);
  const status = built.find((column) => column.field === 'status')!;
  const filter = status
    .filterOperators!.find((operator) => operator.value === 'is')!
    .getApplyFilterFn(
      { field: 'status', operator: 'is', value: 'OPEN' },
      status
    )!;
  const combined = matching.filter((record) =>
    filter(record.status, record, status, apiRef)
  );
  expect(pivot(combined, built).rows).toHaveLength(1);
  expect(pivot(rows, built).rows).toHaveLength(3);
});

test('generated rows are safe for custom getters and status export formatting', () => {
  const built = columns([row('1')], [field('Flag', CustomFieldType.Boolean)]);
  const generated = {
    [GRID_ID_AUTOGENERATED]: 'group',
  } as unknown as ReferralBrowserRowV2;
  const apiRef = { current: undefined as unknown as GridApiPremium };
  for (const column of built) {
    if (column.valueGetter)
      expect(
        column.valueGetter(undefined as never, generated, column, apiRef)
      ).toBeNull();
  }
  const status = built.find((column) => column.field === 'status')!;
  expect(
    status.valueFormatter!('OPEN' as never, generated, status, apiRef)
  ).toBe('Open');
  expect(
    built.find((column) => column.field === 'searchableText')
  ).toMatchObject({ disableExport: true, chartable: false, pivotable: false });
});

test('native Pivot preserves true, false and missing Boolean buckets', () => {
  const rows = [true, false, null].map((Flag, index) =>
    row(String(index), { customFieldValues: { Flag } })
  );
  const result = pivot(
    rows,
    columns(rows, [field('Flag', CustomFieldType.Boolean)]),
    'status',
    'referralCustomField:Flag'
  );
  expect(result.columnGroupingModel?.map((group) => group.headerName)).toEqual([
    'Yes',
    'No',
    '(No value)',
  ]);
  const totals = Object.keys(result.aggregationModel!).map((measure) =>
    GRID_AGGREGATION_FUNCTIONS.sum.apply({
      field: measure,
      values: result.rows.map((record) => record[measure]),
    })
  );
  expect(totals).toEqual([1, 1, 1]);
});

test('native Charts eligibility follows generated Pivot fields and excludes original helpers', () => {
  const rows = [row('1'), row('2', { status: 'CLOSED' })];
  const result = pivot(rows, columns(rows), 'county', 'status');
  const lookup = Object.fromEntries(
    result.columns.map((column) => [
      column.field,
      { chartable: true, ...column },
    ])
  );
  const apiRef = {
    current: {
      state: {
        columns: { lookup },
        pivoting: {
          active: true,
          model: {
            rows: [{ field: 'county' }],
            columns: [{ field: 'status' }],
            values: [{ field: 'referralCount', aggFunc: 'sum' }],
          },
        },
      },
    },
  } as unknown as { current: GridApiPremium };
  const eligible = gridChartableColumnsSelector(apiRef);
  expect(Object.keys(eligible).sort()).toEqual(
    ['county', ...Object.keys(result.aggregationModel!)].sort()
  );
});

test('native CSV serialization keeps aggregated counts numeric and status labels human-readable', () => {
  const serialize = (value: unknown, formattedValue: unknown, type: string) =>
    serializeCellValue(
      { value, formattedValue, colDef: { type } } as Parameters<
        typeof serializeCellValue
      >[0],
      {
        csvOptions: {
          delimiter: ',',
          shouldAppendQuotes: true,
          escapeFormulas: true,
        },
        ignoreValueFormatter: false,
      }
    );
  expect(serialize(3, 3, 'number')).toBe('3');
  expect(serialize('OPEN', 'Open', 'singleSelect')).toBe('Open');
  expect(serialize(['person-1'], 'Megan Smith', 'multiSelect')).toBe(
    'Megan Smith'
  );
});

test('requested organization configurations and newly configured category need no source changes', () => {
  const configurations = [
    {
      fields: [
        field('Referral source', CustomFieldType.String, [
          'Church',
          'School',
          'Hospital',
        ]),
        field('Emergency', CustomFieldType.Boolean),
        field('Notes', CustomFieldType.String),
        field('Needs', CustomFieldType.StringArray),
      ],
      values: { 'Referral source': 'School', Emergency: false },
      role: 'Coordinator',
    },
    {
      fields: [
        field('Program', CustomFieldType.String, [
          'Hosting',
          'Mentoring',
          'Respite',
        ]),
        field('Urgent', CustomFieldType.Boolean),
      ],
      values: { Program: 'Mentoring', Urgent: true },
      role: 'Reviewer',
    },
    { fields: [], values: {}, role: 'Intake worker' },
  ];
  for (const configuration of configurations) {
    const record = row('1', { customFieldValues: configuration.values });
    const built = buildReferralsColumns(
      [record],
      [{ role: configuration.role, options: [] }],
      configuration.fields,
      ['North'],
      false
    );
    expect(
      built
        .filter((column) => column.field.startsWith('referralCustomField:'))
        .map((column) => column.headerName)
    ).toEqual(configuration.fields.map((definition) => definition.name));
    expect(
      built.find((column) => column.field.startsWith('assignmentRole:'))
    ).toMatchObject({
      headerName: configuration.role,
      pivotable: false,
      chartable: false,
    });
    expect(
      built.find((column) => column.field === 'referralCount')
    ).toMatchObject({ availableAggregationFunctions: ['sum'] });
  }
  const record = row('1', { customFieldValues: { Added: 'Option' } });
  const built = columns(
    [record],
    [field('Added', CustomFieldType.String, ['Option'])]
  );
  const added = built.find((column) => column.field.endsWith(':Added'))!;
  expect(added).toMatchObject({
    pivotable: true,
    chartable: true,
    type: 'singleSelect',
  });
  const apiRef = { current: undefined as unknown as GridApiPremium };
  const predicate = added
    .filterOperators!.find((operator) => operator.value === 'is')!
    .getApplyFilterFn(
      { field: added.field, operator: 'is', value: 'Option' },
      added
    )!;
  expect(predicate('Option', record, added, apiRef)).toBe(true);
  expect(added.valueFormatter!('Option' as never, record, added, apiRef)).toBe(
    'Option'
  );
  expect(pivot([record], built, added.field, 'status').rows).toHaveLength(1);
});

test('native Excel serializer preserves numeric aggregated counts and Boolean/date values', () => {
  const record = row('1', { customFieldValues: { Flag: false } });
  const definitions = columns(
    [record],
    [field('Flag', CustomFieldType.Boolean)]
  ).filter((column) =>
    ['referralCount', 'openedAtUtc', 'referralCustomField:Flag'].includes(
      column.field
    )
  );
  const lookup = Object.fromEntries(
    definitions.map((column) => [column.field, column])
  );
  const apiRef = {
    current: {
      state: {
        columns: {
          lookup,
          orderedFields: definitions.map((column) => column.field),
        },
      },
      getRow: () => record,
      getRowNode: () => ({ depth: 0 }),
      getRowValue: (
        value: ReferralBrowserRowV2,
        column: GridColDef<ReferralBrowserRowV2>
      ) =>
        column.field === 'referralCustomField:Flag'
          ? false
          : value[column.field as keyof ReferralBrowserRowV2],
    },
  } as unknown as Parameters<typeof serializeRowUnsafe>[2];
  const serialized = serializeRowUnsafe(
    record.id,
    definitions as Parameters<typeof serializeRowUnsafe>[1],
    apiRef,
    {},
    { escapeFormulas: true }
  );
  expect(serialized.row.referralCount).toBe(1);
  expect(serialized.row['referralCustomField:Flag']).toBe(false);
  expect(serialized.row.openedAtUtc).toBeInstanceOf(Date);
});

test('native filtering engine composes search, status, county, assignment and custom fields', () => {
  const rows = [
    row('1', {
      searchableText: 'John full comment',
      customFieldValues: { Flag: true },
      assignmentPersonIdsByRole: { Worker: ['person-1'] },
    }),
    row('2', {
      searchableText: 'John full comment',
      status: 'CLOSED',
      county: 'South',
      customFieldValues: { Flag: false },
    }),
    row('3', {
      searchableText: 'Other person',
      customFieldValues: { Flag: true },
    }),
  ];
  const built = buildReferralsColumns(
    rows,
    [{ role: 'Worker', options: [{ value: 'person-1', label: 'Jane' }] }],
    [field('Flag', CustomFieldType.Boolean)],
    ['North', 'South'],
    false
  );
  const lookup = Object.fromEntries(
    getInitialColumns(
      built,
      undefined,
      (() => '') as GridApiPremium['getLocaleText']
    )
  );
  const apiRef = {
    current: {
      state: {
        columns: {
          lookup,
          orderedFields: Object.keys(lookup),
          columnVisibilityModel: { searchableText: false },
        },
      },
      rootProps: { ignoreDiacritics: false },
      getColumn: (field: string) => lookup[field],
    },
  } as unknown as Parameters<typeof buildAggregatedFilterApplier>[2];
  const getValue: Parameters<typeof buildAggregatedFilterApplier>[1] = (
    record,
    column
  ) =>
    column.valueGetter
      ? column.valueGetter(undefined as never, record, column, apiRef)
      : record[column.field];
  const items = [
    { id: 1, field: 'status', operator: 'is', value: 'OPEN' },
    { id: 2, field: 'county', operator: 'isAnyOf', value: ['North'] },
    {
      id: 3,
      field: 'assignmentRole:Worker',
      operator: 'contains',
      value: ['person-1'],
    },
    { id: 4, field: 'referralCustomField:Flag', operator: 'is', value: 'true' },
  ];
  const matching = (model: GridFilterModel) => {
    const apply = buildAggregatedFilterApplier(model, getValue, apiRef, true);
    return rows
      .filter((record) => {
        const result = {} as Parameters<typeof apply>[2];
        apply(record, undefined, result);
        return passFilterLogic(
          [result.passingFilterItems],
          [result.passingQuickFilterValues],
          model,
          getValue,
          apiRef,
          {}
        );
      })
      .map((record) => record.id);
  };
  const model: GridFilterModel = {
    items,
    logicOperator: GridLogicOperator.And,
    quickFilterValues: [' JOHN '],
    quickFilterExcludeHiddenColumns: false,
  };
  expect(matching(model)).toEqual(['1']);
  expect(
    matching({
      ...model,
      items: items.slice(0, 2),
      logicOperator: GridLogicOperator.Or,
    })
  ).toEqual(['1']);
  expect(
    matching({
      ...model,
      items: [
        { id: 1, field: 'status', operator: 'is', value: 'CLOSED' },
        items[1],
      ],
      logicOperator: GridLogicOperator.Or,
    })
  ).toEqual(['1', '2']);
  expect(matching({ items: [] })).toEqual(['1', '2', '3']);
});

test('native sorting preserves equal-date source order and does not mutate rows', () => {
  const rows = [
    row('b'),
    row('a'),
    row('c', { openedAtUtc: new Date('2026-02-01') }),
  ];
  const params = {} as Parameters<typeof gridDateComparator>[2];
  const ascending = [...rows].sort((a, b) =>
    gridDateComparator(a.openedAtUtc, b.openedAtUtc, params, params)
  );
  const descending = [...rows].sort(
    (a, b) => -gridDateComparator(a.openedAtUtc, b.openedAtUtc, params, params)
  );
  expect(ascending.map((record) => record.id)).toEqual(['b', 'a', 'c']);
  expect(descending.map((record) => record.id)).toEqual(['c', 'b', 'a']);
  expect(rows.map((record) => record.id)).toEqual(['b', 'a', 'c']);
  expect(
    gridStringOrNumberComparator('ACCEPTED', 'OPEN', params, params)
  ).toBeLessThan(0);
  expect(
    gridStringOrNumberComparator('Alpha', 'Zulu', params, params)
  ).toBeLessThan(0);
});
