# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: CD - Production - .NET+React

concurrency:
  group: continuous_delivery
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - name: Checkout source
      uses: actions/checkout@master
    # Connect to Azure Container Registry 
    - uses: azure/docker-login@v1 
      with:
        login-server: caretogether.azurecr.io 
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }} 
    # Build and publish the .NET backend container via dockerfile 
    - run: |
        docker build src/CareTogether.Api/Dockerfile -t caretogether.azurecr.io/caretogether-api:${{ github.sha }} 
        docker push caretogether.azurecr.io/caretogether-api:${{ github.sha }}  
    # Deploy .NET backend container
    - name: Deploy .NET API to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: caretogether-api
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CARETOGETHER_API }}
        images: 'caretogether.azurecr.io/caretogether-api:${{ github.sha }}'

    # Build React frontend
#   - name: Set up Node.js
#     uses: actions/setup-node@v1
#     with:
#       node-version: '14.x'
#   - name: Cache NPM packages
#     uses: actions/cache@v2
#     with:
#       path: '**/node_modules'
#       key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
#   - name: Install Yarn
#     run: npm install -g yarn
#   - name: Install NPM packages
#     run: yarn install
#     working-directory: src/caretogether-pwa
#   - name: Build React app
#     run: yarn build
#     working-directory: src/caretogether-pwa
    # Deploy React frontend
#   - name: Deploy React PWA to Azure
#     uses: azure/webapps-deploy@v2
#     id: deploy-to-webapp
#     with:
#       app-name: 'caretogether-pwa'
#       slot-name: 'production'
#       publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CARETOGETHER_PWA }}
#       package: src/caretogether-pwa/build
