name: CI - Pull Requests - React PWA

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/caretogether-pwa/**'
      - '.github/workflows/ci-pr-react.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repo
    - name: Checkout source
      uses: actions/checkout@v3
    # Build React frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: src/caretogether-pwa
    - name: Install NPM packages
      run: npm ci
      working-directory: src/caretogether-pwa
    - name: Build React app
      run: npm run build
      working-directory: src/caretogether-pwa
