# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: CD - Production - .NET+React

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    # Build .NET backend
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Publish .NET API release build
      run: dotnet publish --configuration Release --output ${{env.GITHUB_WORKSPACE}}/publish/api
    - name: Upload API artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: api
        path: ${{env.GITHUB_WORKSPACE}}/publish/api
#   - name: Download API artifact from build job
#     uses: actions/download-artifact@v2
#     with:
#       name: api
#   - name: Deploy .NET API to Azure
#     uses: azure/webapps-deploy@v2
#     with:
#       app-name: caretogether
#       slot-name: Production
#       publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F487B40891C940EAAA7EAF30B034F7AE }}
#       package: ${{env.GITHUB_WORKSPACE}}/publish/api

    # Build React frontend
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install Yarn
      run: npm install yarn
    - name: Build React app
      run: |
        cd $CARETOGETHER_PWA_DIR
        yarn build
      env:
        CARETOGETHER_PWA_DIR: ${{env.GITHUB_WORKSPACE}}/src/caretogether-pwa
    - name: Upload PWA artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: pwa
        path: ${{env.GITHUB_WORKSPACE}}/publish/pwa
#   - name: Download PWA artifact from build job
#     uses: actions/download-artifact@v2
#     with:
#       name: pwa
#   - name: 'Deploy to Azure Web App'
#     uses: azure/webapps-deploy@v2
#     id: deploy-to-webapp
#     with:
#       app-name: 'caretogether-pwa'
#       slot-name: 'production'
#       publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
#       package: .
