# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: CD - Production - .NET+React

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repo
    - name: Checkout source
      uses: actions/checkout@master

    # Build .NET backend
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Publish .NET API release build
      run: dotnet publish --configuration Release --self-contained false --output publish/api
#   - name: Upload API artifact for deployment job
#     uses: actions/upload-artifact@v2
#     with:
#       name: api
#       path: publish/api

    # Build React frontend
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install NPM packages
      run: yarn install
      working-directory: src/caretogether-pwa
    - name: Build React app
      run: yarn build
      working-directory: src/caretogether-pwa
#   - name: Upload PWA artifact for deployment job
#     uses: actions/upload-artifact@v2
#     with:
#       name: pwa
#       path: src/caretogether-pwa/build
    
    # Deploy .NET backend
#   - name: Download API artifact from build job
#     uses: actions/download-artifact@v2
#     with:
#       name: api
    - name: Deploy .NET API to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: caretogether-api
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CARETOGETHER_API }}
        package: publish/api
    
    # Deploy React frontend
#   - name: Download PWA artifact from build job
#     uses: actions/download-artifact@v2
#     with:
#       name: pwa
    - name: Deploy React PWA to Azure
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'caretogether-pwa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CARETOGETHER_PWA }}
        package: src/caretogether-pwa/build
